defaults:
  - _self_
  - logging: wandb
  - task: ???
  - alg: ???
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

name: ???
experiment_name: ${name}-${now:%y%m%d-%H%M%S}

hydra:
  run:
    dir: /home/seungyong/train-countdown/tril/outputs/${experiment_name}
