channels:
  - nvidia/label/cuda-11.8.0
  - pytorch
  - conda-forge
dependencies:
  - pytorch==2.0.1
  - torchvision
  - torchaudio
  - cuda
  - pytorch-cuda=11.8
  - compilers
  - sysroot_linux-64==2.17
  - gcc==11.4
  - ninja
  - py-cpuinfo
  - libaio
  - ca-certificates
  - certifi
  - openssl
  - python=3.10
  - pydantic
  - setuptools==69.5.1
